# Generated by Django 3.2.8 on 2021-10-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_hh',
            new_name='social_twitter',
        ),
    ]
